# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ziad\Documents\GitHub\TimeTrackingProject\UI\longBreak.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(795, 600)
        Widget.setStyleSheet("background-color: rgb(133, 92, 119);")
        self.longBreakWidget = QtWidgets.QWidget(Widget)
        self.longBreakWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.longBreakWidget.setStyleSheet("background-color:#4D455D;\n"
"color:rgb(255,255,255);; ")
        self.longBreakWidget.setObjectName("longBreakWidget")
        self.timeLabel = QtWidgets.QLabel(self.longBreakWidget)
        self.timeLabel.setGeometry(QtCore.QRect(190, 130, 411, 201))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(80)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("background-color:#7DB9B6;\n"
"border-radius:30px;")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.startButton = QtWidgets.QPushButton(self.longBreakWidget)
        self.startButton.setGeometry(QtCore.QRect(320, 360, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(22)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.startButton.setObjectName("startButton")
        self.skipButton = QtWidgets.QPushButton(self.longBreakWidget)
        self.skipButton.setGeometry(QtCore.QRect(360, 420, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(16)
        self.skipButton.setFont(font)
        self.skipButton.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.skipButton.setObjectName("skipButton")
        self.goToMainMenuButton = QtWidgets.QPushButton(self.longBreakWidget)
        self.goToMainMenuButton.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(12)
        self.goToMainMenuButton.setFont(font)
        self.goToMainMenuButton.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.goToMainMenuButton.setObjectName("goToMainMenuButton")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.timeLabel.setText(_translate("Widget", "30:00"))
        self.startButton.setText(_translate("Widget", "Start"))
        self.skipButton.setText(_translate("Widget", "Skip"))
        self.goToMainMenuButton.setText(_translate("Widget", "Main Menu"))
