# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Ziad\Documents\GitHub\TimeTrackingProject\UI\pomodoro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(795, 600)
        Widget.setStyleSheet("background-color: rgb(133, 92, 119);")
        self.Pomodoro = QtWidgets.QWidget(Widget)
        self.Pomodoro.setGeometry(QtCore.QRect(0, 0, 800, 600))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.Pomodoro.setFont(font)
        self.Pomodoro.setStyleSheet("background-color: #4D455D;\n"
"color:rgb(255, 255, 255);")
        self.Pomodoro.setObjectName("Pomodoro")
        self.timeLabel = QtWidgets.QLabel(self.Pomodoro)
        self.timeLabel.setGeometry(QtCore.QRect(150, 210, 511, 191))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(80)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("background-color:#7DB9B6;\n"
"border-radius:10px;\n"
"color: #E96479")
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.addTaskWidget = QtWidgets.QWidget(self.Pomodoro)
        self.addTaskWidget.setEnabled(True)
        self.addTaskWidget.setGeometry(QtCore.QRect(150, 90, 511, 111))
        self.addTaskWidget.setStyleSheet("background-color:#7DB9B6;\n"
"border-radius:10px;\n"
"")
        self.addTaskWidget.setObjectName("addTaskWidget")
        self.addYourTasksText = QtWidgets.QLabel(self.addTaskWidget)
        self.addYourTasksText.setGeometry(QtCore.QRect(40, 20, 391, 20))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        self.addYourTasksText.setFont(font)
        self.addYourTasksText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.addYourTasksText.setStyleSheet("background-color:rgba(255, 255, 255, 0);")
        self.addYourTasksText.setAlignment(QtCore.Qt.AlignCenter)
        self.addYourTasksText.setObjectName("addYourTasksText")
        self.taskInput = QtWidgets.QLineEdit(self.addTaskWidget)
        self.taskInput.setGeometry(QtCore.QRect(30, 50, 331, 21))
        self.taskInput.setStyleSheet("background-color: rgba(217, 217, 217, 66);\n"
"border-radius:10px;\n"
"")
        self.taskInput.setText("")
        self.taskInput.setObjectName("taskInput")
        self.addTask = QtWidgets.QPushButton(self.addTaskWidget)
        self.addTask.setGeometry(QtCore.QRect(370, 50, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(12)
        self.addTask.setFont(font)
        self.addTask.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.addTask.setObjectName("addTask")
        self.yourTasksText = QtWidgets.QLabel(self.addTaskWidget)
        self.yourTasksText.setGeometry(QtCore.QRect(10, 80, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        self.yourTasksText.setFont(font)
        self.yourTasksText.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yourTasksText.setStyleSheet("background-color:rgba(255, 255, 255, 0);")
        self.yourTasksText.setObjectName("yourTasksText")
        self.tasksCombo = QtWidgets.QComboBox(self.addTaskWidget)
        self.tasksCombo.setGeometry(QtCore.QRect(150, 80, 331, 21))
        self.tasksCombo.setStyleSheet("background-color: rgb(121, 179, 176);\n"
"border-radius:0px;\n"
"")
        self.tasksCombo.setObjectName("tasksCombo")
        self.pomodoroSession = QtWidgets.QLabel(self.Pomodoro)
        self.pomodoroSession.setGeometry(QtCore.QRect(160, 30, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(20)
        font.setUnderline(False)
        self.pomodoroSession.setFont(font)
        self.pomodoroSession.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pomodoroSession.setAlignment(QtCore.Qt.AlignCenter)
        self.pomodoroSession.setObjectName("pomodoroSession")
        self.numberOfSession = QtWidgets.QLabel(self.Pomodoro)
        self.numberOfSession.setGeometry(QtCore.QRect(470, 10, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(40)
        font.setUnderline(False)
        self.numberOfSession.setFont(font)
        self.numberOfSession.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.numberOfSession.setAlignment(QtCore.Qt.AlignCenter)
        self.numberOfSession.setObjectName("numberOfSession")
        self.startStopButton = QtWidgets.QPushButton(self.Pomodoro)
        self.startStopButton.setGeometry(QtCore.QRect(320, 410, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(20)
        self.startStopButton.setFont(font)
        self.startStopButton.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.startStopButton.setObjectName("startStopButton")
        self.doneButton = QtWidgets.QPushButton(self.Pomodoro)
        self.doneButton.setGeometry(QtCore.QRect(270, 460, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(12)
        self.doneButton.setFont(font)
        self.doneButton.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.doneButton.setObjectName("doneButton")
        self.notFinishedButton = QtWidgets.QWidget(self.Pomodoro)
        self.notFinishedButton.setEnabled(True)
        self.notFinishedButton.setGeometry(QtCore.QRect(110, 500, 581, 61))
        self.notFinishedButton.setStyleSheet("background-color:#7DB9B6;\n"
"border-radius:10px;\n"
"")
        self.notFinishedButton.setObjectName("notFinishedButton")
        self.tasksBelow = QtWidgets.QLabel(self.notFinishedButton)
        self.tasksBelow.setGeometry(QtCore.QRect(10, 20, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(14)
        font.setBold(False)
        font.setUnderline(False)
        self.tasksBelow.setFont(font)
        self.tasksBelow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tasksBelow.setStyleSheet("background-color:rgba(255, 255, 255, 0);")
        self.tasksBelow.setAlignment(QtCore.Qt.AlignCenter)
        self.tasksBelow.setObjectName("tasksBelow")
        self.labelAsNotFinishedButton = QtWidgets.QPushButton(self.notFinishedButton)
        self.labelAsNotFinishedButton.setGeometry(QtCore.QRect(420, 20, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(9)
        self.labelAsNotFinishedButton.setFont(font)
        self.labelAsNotFinishedButton.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.labelAsNotFinishedButton.setObjectName("labelAsNotFinishedButton")
        self.tasksCombo_2 = QtWidgets.QComboBox(self.notFinishedButton)
        self.tasksCombo_2.setGeometry(QtCore.QRect(90, 20, 311, 21))
        self.tasksCombo_2.setStyleSheet("background-color: rgb(121, 179, 176);\n"
"border-radius:0px;\n"
"")
        self.tasksCombo_2.setObjectName("tasksCombo_2")
        self.goToMainMenuButton = QtWidgets.QPushButton(self.Pomodoro)
        self.goToMainMenuButton.setGeometry(QtCore.QRect(10, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Chalkboard")
        font.setPointSize(12)
        self.goToMainMenuButton.setFont(font)
        self.goToMainMenuButton.setStyleSheet("background-color:#F5E9CF;\n"
"border-radius:10px;\n"
"color:#4D455D;")
        self.goToMainMenuButton.setObjectName("goToMainMenuButton")
        self.timeLabel.raise_()
        self.addTaskWidget.raise_()
        self.pomodoroSession.raise_()
        self.startStopButton.raise_()
        self.doneButton.raise_()
        self.notFinishedButton.raise_()
        self.goToMainMenuButton.raise_()
        self.numberOfSession.raise_()

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.timeLabel.setText(_translate("Widget", "25:00"))
        self.addYourTasksText.setText(_translate("Widget", "Add your task(s) for this Pomodoro session"))
        self.addTask.setText(_translate("Widget", "Add Task"))
        self.yourTasksText.setText(_translate("Widget", "Your tasks:"))
        self.pomodoroSession.setText(_translate("Widget", "Pomodoro Session"))
        self.numberOfSession.setText(_translate("Widget", "1"))
        self.startStopButton.setText(_translate("Widget", "Start"))
        self.doneButton.setText(_translate("Widget", "I\'am done with this session"))
        self.tasksBelow.setText(_translate("Widget", "Tasks:"))
        self.labelAsNotFinishedButton.setText(_translate("Widget", "Label as not finished"))
        self.goToMainMenuButton.setText(_translate("Widget", "Main Menu"))
